
server:
  port: 8080

binance:
  spot_ws-url: wss://stream.binance.com:9443/stream
  futures_ws-url: wss://fstream.binance.com/stream
  spot-symbols: btcusdt, ethusdt, solusdt
  futures-symbols: BZUSDT

ohlc:
  timeframes: 60
#  timeframes: 15, 30, 60

alerts:
  price-thresholds:
    BTCUSDT:
      upper: 90000
      lower: 85000
    ETHUSDT:
      upper: 4000
      lower: 2700

  percent-change:
    BTCUSDT:
      timeframe: 60
      candles: 3
      percent: 0.1
    ETHUSDT:
      timeframe: 60
      candles: 3
      percent: 0.1
    SOLUSDT:
      timeframe: 60
      candles: 3
      percent: 0.1
    BZUSDT:
      timeframe: 60
      candles: 3
      percent: 0.1

  impulse-move:
    BTCUSDT:
      timeframe: 60
      direction-ratio: 0.75
      min-total-move-percent: 0.1
      acceleration-factor: 1.2
    ETHUSDT:
      timeframe: 60
      direction-ratio: 0.75
      min-total-move-percent: 0.8
      acceleration-factor: 1.5
    BZUSDT:
      timeframe: 60
      direction-ratio: 0.75
      min-total-move-percent: 0.8
      acceleration-factor: 1.5

rules:
  impulse-move:
    is-active: false



spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:marketanalyse
    driver-class-name: org.h2.Driver
    username: sa
    password: password
#    url: jdbc:postgresql://localhost:5433/marketanalyse
#    username: marketanalyse
#    password: ${CRYPASS}
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging:
  level:
    root: INFO
    com.example.cryptoanalyzer.rules.PercentChangeRule: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: com.example.cryptoanalyzer.web
